version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "04:00"
      timezone: Europe/Brussels
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
