function run_separability_oracle()
% RUN_SEPARABILITY_ORACLE Generate deterministic QETLAB separability fixtures.
%
% QETLAB source revision:
% d8589610f00cff106537268dee2e2a1153f3a601
% QETLAB is Copyright 2014 Nathaniel Johnston and Alessandro Cosentino,
% BSD-2-Clause. Full upstream terms: licenses/QETLAB-LICENSE.txt.

qetlab_path = getenv('QET_ORACLE_QETLAB_PATH');
output_path = getenv('QET_ORACLE_OUTPUT');
qetlab_commit = getenv('QET_ORACLE_QETLAB_COMMIT');
if isempty(qetlab_path) || isempty(output_path) || isempty(qetlab_commit)
    error('QuantumEntanglementTools:OracleConfiguration', ...
        'QETLAB path, output path, and commit environment variables are required.');
end
required_files = {'IsSeparable.m', 'LocalDistinguishability.m', ...
    'UPBSepDistinguishable.m'};
for index = 1:length(required_files)
    if ~exist(fullfile(qetlab_path, required_files{index}), 'file')
        error('QuantumEntanglementTools:OracleConfiguration', ...
            'The selected QETLAB checkout does not contain %s.', ...
            required_files{index});
    end
end

helpers_path = fullfile(qetlab_path, 'helpers');
addpath(qetlab_path);
addpath(helpers_path);
cleanup_path = onCleanup(@() remove_qetlab_paths(qetlab_path, helpers_path));
if exist('OCTAVE_VERSION', 'builtin')
    octave_compat_path = fullfile(fileparts(mfilename('fullpath')), 'octave_compat');
    addpath(octave_compat_path);
    cleanup_octave_compat = onCleanup(@() rmpath(octave_compat_path));
end

tol = eps^(3/8);
ket00 = [1; 0; 0; 0];
phi2 = [1; 0; 0; 1] / sqrt(2);
phi3 = reshape(eye(3), 9, 1) / sqrt(3);
rho_product = ket00 * ket00';
rho_bell = phi2 * phi2';
rho_mixed_3 = eye(9) / 9;
rho_isotropic_separable = 0.8 * eye(9) / 9 + 0.2 * (phi3 * phi3');
rho_isotropic_entangled = 0.7 * eye(9) / 9 + 0.3 * (phi3 * phi3');
rho_one_local = diag([0.4, 0.3, 0.2, 0.1]);

fixtures = struct( ...
    'name', {}, ...
    'dims', {}, ...
    'matrix_dims', {}, ...
    'matrix_real', {}, ...
    'matrix_imaginary', {}, ...
    'qetlab_sep', {}, ...
    'expected_status', {}, ...
    'certificate_family', {}, ...
    'atol', {}, ...
    'rtol', {});

fixtures(end + 1) = separability_fixture( ...
    'one_dimensional_local_factor', rho_one_local, [1, 4], ...
    'separable', 'one_dimensional_local_factor', tol);
fixtures(end + 1) = separability_fixture( ...
    'two_qubit_product', rho_product, [2, 2], ...
    'separable', 'ppt_low_dimension', tol);
fixtures(end + 1) = separability_fixture( ...
    'two_qubit_bell', rho_bell, [2, 2], ...
    'entangled', 'negative_partial_transpose', tol);
fixtures(end + 1) = separability_fixture( ...
    'three_by_three_maximally_mixed', rho_mixed_3, [3, 3], ...
    'separable', 'maximally_mixed_neighborhood', tol);
fixtures(end + 1) = separability_fixture( ...
    'three_by_three_isotropic_q_0_2', rho_isotropic_separable, [3, 3], ...
    'separable', 'rank_one_identity_perturbation', tol);
fixtures(end + 1) = separability_fixture( ...
    'three_by_three_isotropic_q_0_3', rho_isotropic_entangled, [3, 3], ...
    'entangled', 'negative_partial_transpose', tol);

% Reviewed unsafe source behavior: IsSeparable silently trace-normalizes.
trace_two_qetlab_sep = IsSeparable(2 * rho_bell, [2, 2], 0, 0, tol);

local_fixtures = struct( ...
    'name', {}, ...
    'input_dims', {}, ...
    'state_real', {}, ...
    'state_imaginary', {}, ...
    'priors', {}, ...
    'qetlab_distance', {}, ...
    'qetlab_measurement_dims', {}, ...
    'qetlab_dual_dims', {}, ...
    'native_measurement_dimension', {});

[single_distance, single_measurement, single_dual] = ...
    LocalDistinguishability(2 * ket00, ...
        'P', 1, 'DIM', [2, 2], 'COPIES', 2, ...
        'PPT', true, 'BOS', true, 'TOL', tol);
local_fixtures(end + 1) = local_fixture( ...
    'single_scaled_pure_state', 2 * ket00, 1, single_distance, ...
    single_measurement, single_dual, 4);

deterministic_states = [2 * ket00, [0; 0; 0; 3]];
[deterministic_distance, deterministic_measurement, deterministic_dual] = ...
    LocalDistinguishability(deterministic_states, ...
        'P', [1, 0], 'DIM', [2, 2], 'COPIES', 2, ...
        'PPT', true, 'BOS', true, 'TOL', tol);
local_fixtures(end + 1) = local_fixture( ...
    'deterministic_prior_scaled_pure_states', deterministic_states, [1, 0], ...
    deterministic_distance, deterministic_measurement, deterministic_dual, 4);

metadata = struct();
metadata.schema = 'quantum-entanglement-tools-oracle-v1';
metadata.tier = 'WP6-separability';
metadata.generated_utc = [datestr(now, 30), 'Z'];
metadata.qetlab_commit = qetlab_commit;
metadata.qetlab_license = 'BSD-2-Clause';
metadata.platform = computer;
metadata.fixture_count = length(fixtures);
metadata.local_fixture_count = length(local_fixtures);
metadata.source_free_fixture = true;
metadata.is_separable_sha256 = ...
    'be078f7087c1d64ca8c1e29778fbb78690d9d06b569dc6a617cbb1b5a3656f97';
metadata.local_distinguishability_sha256 = ...
    'a83329f5ab1d4e751ad55748a56907dfa25bb7241909dad5c0222a4f55d47853';
metadata.upb_sep_distinguishable_sha256 = ...
    '651c0ff6d8a59d8da6bf1d0632e7e118362b02e9742262e576c39e7aa4491035';
metadata.trace_two_bell_accepted_sep = trace_two_qetlab_sep;
metadata.local_trivial_measurement_shape_defect = ...
    ['The pinned trivial branch calls eye(dim), where DIM is the local ', ...
     'dimension tuple. For a four-dimensional state with DIM=[2,2], it ', ...
     'returns a 2-by-2 effect instead of the required 4-by-4 effect.'];
metadata.is_separable_stale_update_defect = ...
    ['The pinned randomized subtraction branch computes XSeig2 and e_norm2 ', ...
     'from the previous Xsep and XSeig instead of the proposed Xsep2.'];
metadata.rank_one_tolerance_promotion = ...
    ['The pinned rank-one identity-perturbation branch treats numerically ', ...
     'near-equal trailing eigenvalues as an exact sufficient hypothesis. ', ...
     'The native API keeps that floating boundary unknown unless the ', ...
     'represented trailing eigenvalues are exactly equal.'];
metadata.upb_complex_transpose_defect = ...
    ['The pinned UPB replacement search uses the nonconjugating transpose ', ...
     'V.'' when constructing null spaces for complex local factors.'];
metadata.cvx_available = exist('cvx_begin', 'file') ~= 0;
metadata.evidence_scope = ...
    ['IsSeparable strength-zero branches and LocalDistinguishability ', ...
     'one-state or deterministic-prior branches only. These routes are ', ...
     'deterministic and do not invoke CVX. Local nontrivial hierarchy and ', ...
     'UPBSepDistinguishable oracle execution were unavailable because CVX ', ...
     'was not installed; Julia optional-backend tests use Hypatia and SCS.'];
if exist('OCTAVE_VERSION', 'builtin')
    metadata.engine = 'Octave';
    metadata.engine_version = OCTAVE_VERSION;
    metadata.matlab_compatible_oracle = false;
else
    metadata.engine = 'MATLAB';
    metadata.engine_version = version;
    metadata.matlab_compatible_oracle = true;
end

payload = struct();
payload.metadata = metadata;
payload.fixtures = fixtures;
payload.local_fixtures = local_fixtures;
encoded = jsonencode(payload);
output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~exist(output_directory, 'dir')
    mkdir(output_directory);
end
file_id = fopen(output_path, 'w');
if file_id < 0
    error('QuantumEntanglementTools:OracleOutput', ...
        'Could not open the oracle output path for writing.');
end
cleanup_file = onCleanup(@() fclose(file_id));
fwrite(file_id, encoded, 'char');
fwrite(file_id, sprintf('\n'), 'char');
fprintf(['Wrote %d IsSeparable and %d LocalDistinguishability fixtures ', ...
    'to %s using %s %s.\n'], ...
    length(fixtures), length(local_fixtures), output_path, ...
    metadata.engine, metadata.engine_version);
end

function fixture = separability_fixture( ...
    name, matrix, dims, expected_status, certificate_family, tol)
    sep = IsSeparable(matrix, dims, 0, 0, tol);
    fixture = struct();
    fixture.name = name;
    fixture.dims = reshape(dims, 1, []);
    fixture.matrix_dims = size(matrix);
    fixture.matrix_real = reshape(full(real(matrix)), 1, []);
    fixture.matrix_imaginary = reshape(full(imag(matrix)), 1, []);
    fixture.qetlab_sep = sep;
    fixture.expected_status = expected_status;
    fixture.certificate_family = certificate_family;
    fixture.atol = 2e-10;
    fixture.rtol = 2e-10;
end

function fixture = local_fixture( ...
    name, states, priors, distance, measurement, dual, native_dimension)
    fixture = struct();
    fixture.name = name;
    fixture.input_dims = size(states);
    fixture.state_real = reshape(full(real(states)), 1, []);
    fixture.state_imaginary = reshape(full(imag(states)), 1, []);
    fixture.priors = reshape(priors, 1, []);
    fixture.qetlab_distance = distance;
    fixture.qetlab_measurement_dims = size(measurement);
    fixture.qetlab_dual_dims = size(dual);
    fixture.native_measurement_dimension = native_dimension;
end

function remove_qetlab_paths(qetlab_path, helpers_path)
    rmpath(helpers_path);
    rmpath(qetlab_path);
end
