function run_channel_optimization_oracle()
% RUN_CHANNEL_OPTIMIZATION_ORACLE Generate deterministic solver-free fixtures.
%
% QETLAB source revision:
% d8589610f00cff106537268dee2e2a1153f3a601
% QETLAB is Copyright 2014 Nathaniel Johnston, BSD-2-Clause.
% Full upstream terms: licenses/QETLAB-LICENSE.txt.

qetlab_path = getenv('QET_ORACLE_QETLAB_PATH');
output_path = getenv('QET_ORACLE_OUTPUT');
qetlab_commit = getenv('QET_ORACLE_QETLAB_COMMIT');
if isempty(qetlab_path) || isempty(output_path) || isempty(qetlab_commit)
    error('QuantumEntanglementTools:OracleConfiguration', ...
        'QETLAB path, output path, and commit environment variables are required.');
end
required_files = { ...
    'DiamondNorm.m', ...
    'CBNorm.m', ...
    'ChannelDistinguishability.m', ...
    'MaximumOutputFidelity.m' ...
};
for index = 1:length(required_files)
    if ~exist(fullfile(qetlab_path, required_files{index}), 'file')
        error('QuantumEntanglementTools:OracleConfiguration', ...
            'The selected QETLAB checkout is missing %s.', required_files{index});
    end
end

helpers_path = fullfile(qetlab_path, 'helpers');
addpath(qetlab_path);
addpath(helpers_path);
cleanup_path = onCleanup(@() remove_qetlab_paths(qetlab_path, helpers_path));

identity = eye(2);
pauli_z = diag([1, -1]);
dephase_zero = [1, 0; 0, 0];
dephase_one = [0, 0; 0, 1];
reset_zero_0 = [1, 0; 0, 0];
reset_zero_1 = [0, 1; 0, 0];
reset_one_0 = [0, 0; 1, 0];
reset_one_1 = [0, 0; 0, 1];

fixtures = struct( ...
    'name', {}, ...
    'routine', {}, ...
    'first_input_dimension', {}, ...
    'first_output_dimension', {}, ...
    'first_kraus_dims', {}, ...
    'first_kraus_real', {}, ...
    'first_kraus_imaginary', {}, ...
    'second_input_dimension', {}, ...
    'second_output_dimension', {}, ...
    'second_kraus_dims', {}, ...
    'second_kraus_real', {}, ...
    'second_kraus_imaginary', {}, ...
    'priors', {}, ...
    'expected_value', {}, ...
    'native_expected_value', {}, ...
    'deviation', {}, ...
    'atol', {}, ...
    'rtol', {});

fixtures(end + 1) = oracle_fixture( ...
    'diamond_identity', 'diamond_norm', {identity}, {}, [], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'diamond_rectangular_trace', 'diamond_norm', ...
    {[1, 0]; [0, 1]}, {}, [], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'diamond_scaled_identity', 'diamond_norm', {2 * identity}, {}, [], 4, '');
fixtures(end + 1) = oracle_fixture( ...
    'cb_identity', 'cb_norm', {identity}, {}, [], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'cb_reset', 'cb_norm', {reset_zero_0; reset_zero_1}, {}, [], 2, '');
fixtures(end + 1) = oracle_fixture( ...
    'channel_identical_unequal', 'channel_distinguishability', ...
    {identity}, {identity}, [0.8, 0.2], 0.8, ...
    'pinned_missing_channel_Helstrom_affine_conversion');
fixtures(end + 1) = oracle_fixture( ...
    'channel_deterministic', 'channel_distinguishability', ...
    {identity}, {dephase_zero; dephase_one}, [1, 0], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'maximum_identical', 'maximum_output_fidelity', ...
    {identity}, {identity}, [], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'maximum_orthogonal_replacers', 'maximum_output_fidelity', ...
    {reset_zero_0; reset_zero_1}, {reset_one_0; reset_one_1}, [], 0, '');
fixtures(end + 1) = oracle_fixture( ...
    'maximum_identity_dephasing', 'maximum_output_fidelity', ...
    {identity}, {dephase_zero; dephase_one}, [], 1, '');
fixtures(end + 1) = oracle_fixture( ...
    'maximum_rank_truncation_defect', 'maximum_output_fidelity', ...
    {identity}, {0.8 * identity; 0.6 * pauli_z}, [], 1, ...
    'pinned_minimum_Kraus_rank_truncation');

negative_prior_value = ChannelDistinguishability( ...
    {identity}, {dephase_zero; dephase_one}, [1.1, -0.1]);

metadata = struct();
metadata.schema = 'quantum-entanglement-tools-oracle-v1';
metadata.tier = 'WP4-channel-optimization';
metadata.generated_utc = [datestr(now, 30), 'Z'];
metadata.qetlab_commit = qetlab_commit;
metadata.qetlab_license = 'BSD-2-Clause';
metadata.platform = computer;
metadata.fixture_count = length(fixtures);
metadata.source_free_fixture = true;
metadata.cvx_used = false;
metadata.diamond_norm_sha256 = ...
    'a26804a1acf940b90a90d0b1fc67874cc30c0b075285ceb51849b3a0ffeccbb3';
metadata.cb_norm_sha256 = ...
    '04c2dd5cfe2fb6d1864b51b58fd8028018eb3a4c53fe8a6d9b9933f05d931d2c';
metadata.channel_distinguishability_sha256 = ...
    'dc579aefa18c9cfb11c2975e0191b93dfaaf930664b76b05b54021e38c8155f5';
metadata.maximum_output_fidelity_sha256 = ...
    '8a8b0900640db599558582d53683012e7c35be8f226b2864ac146ec91d1fc1b0';
metadata.negative_prior_accepted_value = negative_prior_value;
metadata.channel_probability_defect = ...
    ['The pinned non-deterministic branch returns only ', ...
     '||p1*Phi-p2*Psi||_diamond. The channel Holevo--Helstrom success ', ...
     'probability is (1+that norm)/2 for normalized priors.'];
metadata.maximum_output_fidelity_defect = ...
    ['The pinned routine pairs only the first min(Kraus ranks) canonical ', ...
     'Kraus operators. For identity versus the channel with Kraus ', ...
     '{0.8*I,0.6*Z}, it returns 0.8 although the common |0> output ', ...
     'certifies maximum output fidelity 1.'];
metadata.evidence_scope = ...
    ['Only branches that execute without CVX are recorded: completely ', ...
     'positive/scalar channel-norm shortcuts, deterministic or positive ', ...
     'weighted channel differences, and maximum-output-fidelity cases ', ...
     'whose derived diamond-norm map takes a solver-free branch. Hypatia ', ...
     'and SCS evidence for the general SDPs is maintained separately.'];
if exist('OCTAVE_VERSION', 'builtin')
    metadata.engine = 'Octave';
    metadata.engine_version = OCTAVE_VERSION;
    metadata.matlab_compatible_oracle = false;
else
    metadata.engine = 'MATLAB';
    metadata.engine_version = version;
    metadata.matlab_compatible_oracle = true;
end

payload = struct();
payload.metadata = metadata;
payload.fixtures = fixtures;
encoded = jsonencode(payload);
output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~exist(output_directory, 'dir')
    mkdir(output_directory);
end
file_id = fopen(output_path, 'w');
if file_id < 0
    error('QuantumEntanglementTools:OracleOutput', ...
        'Could not open the oracle output path for writing.');
end
cleanup_file = onCleanup(@() fclose(file_id));
fwrite(file_id, encoded, 'char');
fwrite(file_id, sprintf('\n'), 'char');
fprintf('Wrote %d channel-optimization fixtures to %s using %s %s.\n', ...
    length(fixtures), output_path, metadata.engine, metadata.engine_version);
end

function fixture = oracle_fixture( ...
    name, routine, first_kraus, second_kraus, priors, native_expected, deviation)

switch routine
    case 'diamond_norm'
        value = DiamondNorm(first_kraus);
    case 'cb_norm'
        value = CBNorm(first_kraus);
    case 'channel_distinguishability'
        value = ChannelDistinguishability(first_kraus, second_kraus, priors);
    case 'maximum_output_fidelity'
        value = MaximumOutputFidelity(first_kraus, second_kraus);
    otherwise
        error('QuantumEntanglementTools:OracleFixture', ...
            'Unreviewed oracle routine %s.', routine);
end

[first_dims, first_real, first_imaginary, first_input, first_output] = ...
    flatten_kraus(first_kraus);
[second_dims, second_real, second_imaginary, second_input, second_output] = ...
    flatten_kraus(second_kraus);
fixture = struct();
fixture.name = name;
fixture.routine = routine;
fixture.first_input_dimension = first_input;
fixture.first_output_dimension = first_output;
fixture.first_kraus_dims = first_dims;
fixture.first_kraus_real = first_real;
fixture.first_kraus_imaginary = first_imaginary;
fixture.second_input_dimension = second_input;
fixture.second_output_dimension = second_output;
fixture.second_kraus_dims = second_dims;
fixture.second_kraus_real = second_real;
fixture.second_kraus_imaginary = second_imaginary;
fixture.priors = reshape(priors, 1, []);
fixture.expected_value = value;
fixture.native_expected_value = native_expected;
fixture.deviation = deviation;
fixture.atol = 2e-10;
fixture.rtol = 2e-10;
end

function [dims, real_data, imaginary_data, input_dim, output_dim] = ...
    flatten_kraus(kraus)
if isempty(kraus)
    dims = [0, 0, 0];
    real_data = [];
    imaginary_data = [];
    input_dim = 0;
    output_dim = 0;
    return
end
output_dim = size(kraus{1}, 1);
input_dim = size(kraus{1}, 2);
count = length(kraus);
data = cat(3, kraus{:});
dims = [output_dim, input_dim, count];
real_data = reshape(full(real(data)), 1, []);
imaginary_data = reshape(full(imag(data)), 1, []);
end

function remove_qetlab_paths(qetlab_path, helpers_path)
rmpath(helpers_path);
rmpath(qetlab_path);
end
