function run_tier_e_matrix_analysis_oracle()
% RUN_TIER_E_MATRIX_ANALYSIS_ORACLE Generate deterministic matrix-analysis fixtures.
%
% Common mathematical cases are recorded as agreement fixtures. Reviewed
% QETLAB behaviors that deliberately differ from the Julia-native API are
% classified separately and must never become native expected values.
%
% QETLAB source revision:
% d8589610f00cff106537268dee2e2a1153f3a601
% QETLAB is Copyright 2014 Nathaniel Johnston and named coauthors,
% BSD-2-Clause. Full upstream terms: licenses/QETLAB-LICENSE.txt.

qetlab_path = getenv('QET_ORACLE_QETLAB_PATH');
output_path = getenv('QET_ORACLE_OUTPUT');
qetlab_commit = getenv('QET_ORACLE_QETLAB_COMMIT');

if isempty(qetlab_path) || isempty(output_path) || isempty(qetlab_commit)
    error('QuantumEntanglementTools:OracleConfiguration', ...
        'QETLAB path, output path, and commit environment variables are required.');
end
required_files = { ...
    'Majorizes.m', ...
    'ElemSymPoly.m', ...
    'CompoundMatrix.m', ...
    'AdditiveCompoundMatrix.m'};
for file_index = 1:length(required_files)
    if ~exist(fullfile(qetlab_path, required_files{file_index}), 'file')
        error('QuantumEntanglementTools:OracleConfiguration', ...
            'The selected QETLAB checkout is missing %s.', ...
            required_files{file_index});
    end
end

helpers_path = fullfile(qetlab_path, 'helpers');
addpath(qetlab_path);
addpath(helpers_path);
cleanup_path = onCleanup(@() remove_qetlab_paths(qetlab_path, helpers_path));

fixtures = struct( ...
    'name', {}, ...
    'rows', {}, ...
    'columns', {}, ...
    'real', {}, ...
    'imaginary', {}, ...
    'comparison', {}, ...
    'atol', {}, ...
    'rtol', {}, ...
    'classification', {});

% Agreement fixtures: these values have unambiguous mathematical meanings.
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_vector_true', Majorizes([4; 1; 1], [3; 2; 1]), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_vector_false', Majorizes([3; 2; 1], [4; 1; 1]), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_matrix_singular_values_true', ...
    Majorizes(diag([3, 1]), diag([2, 2])), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_complex_matrix_singular_values_true', ...
    Majorizes(diag([3i, -1]), diag([2, 2])), ...
    'exact', 0, 0, 'agreement');

polynomial_values = [1; 2; 3; 4];
complex_polynomial_values = [1 + 2i; -3 + 1i; 2 - 1i];
fixtures(end + 1) = oracle_fixture( ...
    'elem_sym_poly_order_zero', ElemSymPoly(polynomial_values, 0), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'elem_sym_poly_order_two', ElemSymPoly(polynomial_values, 2), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'elem_sym_poly_order_full', ElemSymPoly(polynomial_values, 4), ...
    'exact', 0, 0, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'elem_sym_poly_complex_order_two', ...
    ElemSymPoly(complex_polynomial_values, 2), ...
    'normwise', 5e-13, 5e-13, 'agreement');

square_matrix = [1, 2, 3; 4, 5, 6; 7, 8, 10];
rectangular_matrix = [1, 2; 3, 5; 7, 11];
complex_matrix = [1 + 1i, 2; 3i, 4 - 1i];
fixtures(end + 1) = oracle_fixture( ...
    'compound_order_zero', CompoundMatrix(square_matrix, 0), ...
    'normwise', 5e-13, 5e-13, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'compound_square_order_two', CompoundMatrix(square_matrix, 2), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'compound_square_order_three', CompoundMatrix(square_matrix, 3), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'compound_rectangular_order_two', ...
    CompoundMatrix(rectangular_matrix, 2), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'compound_complex_order_two', CompoundMatrix(complex_matrix, 2), ...
    'normwise', 5e-12, 5e-12, 'agreement');

diagonal_matrix = diag([-2, 0.5, 3, 7]);
fixtures(end + 1) = oracle_fixture( ...
    'additive_order_one', AdditiveCompoundMatrix(square_matrix, 1), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'additive_order_two', AdditiveCompoundMatrix(square_matrix, 2), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'additive_order_full_trace', AdditiveCompoundMatrix(square_matrix, 3), ...
    'normwise', 5e-12, 5e-12, 'agreement');
fixtures(end + 1) = oracle_fixture( ...
    'additive_diagonal_order_two', ...
    AdditiveCompoundMatrix(diagonal_matrix, 2), ...
    'normwise', 5e-12, 5e-12, 'agreement');

% Reviewed discrepancies: record upstream behavior as evidence, not as a native
% mathematical expectation.
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_weak_total_qetlab_true', Majorizes([2; 0], [1; 0]), ...
    'exact', 0, 0, 'reviewed_discrepancy');
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_negative_padding_qetlab_false', ...
    Majorizes([1; -1], [1; 0; -1]), ...
    'exact', 0, 0, 'reviewed_discrepancy');
fixtures(end + 1) = oracle_fixture( ...
    'majorizes_row_matrix_qetlab_vector_semantics', ...
    Majorizes([1, 1], [sqrt(2), 0]), ...
    'exact', 0, 0, 'reviewed_discrepancy');
fixtures(end + 1) = oracle_fixture( ...
    'compound_rectangular_high_order_qetlab_zero_by_zero', ...
    CompoundMatrix(zeros(2, 3), 3), ...
    'exact', 0, 0, 'reviewed_discrepancy');

additive_order_zero_error = 0;
try
    AdditiveCompoundMatrix(eye(2), 0);
catch
    additive_order_zero_error = 1;
end
fixtures(end + 1) = oracle_fixture( ...
    'additive_order_zero_qetlab_error', additive_order_zero_error, ...
    'exact', 0, 0, 'reviewed_discrepancy');

classifications = {fixtures.classification};
agreement_count = sum(strcmp(classifications, 'agreement'));
discrepancy_count = ...
    sum(strcmp(classifications, 'reviewed_discrepancy'));

metadata = struct();
metadata.schema = 'quantum-entanglement-tools-oracle-v1';
metadata.tier = 'E-matrix-analysis';
metadata.generated_utc = [datestr(now, 30), 'Z'];
metadata.qetlab_commit = qetlab_commit;
metadata.qetlab_license = 'BSD-2-Clause';
metadata.platform = computer;
metadata.fixture_count = length(fixtures);
metadata.agreement_fixture_count = agreement_count;
metadata.reviewed_discrepancy_fixture_count = discrepancy_count;
metadata.source_free_fixture = true;
metadata.reviewed_majorization_total_semantics = ...
    ['QETLAB checks prefix dominance without equal-total validation; ', ...
     'the native API implements strong majorization'];
metadata.reviewed_majorization_padding_semantics = ...
    ['QETLAB sorts before appending zeros, which changes unequal-length ', ...
     'negative-vector behavior'];
metadata.reviewed_row_matrix_semantics = ...
    ['QETLAB treats one-row matrices as vectors; Julia AbstractMatrix ', ...
     'inputs use singular values'];
metadata.reviewed_rectangular_compound_semantics = ...
    ['QETLAB returns 0-by-0 when order exceeds min(m,n); the native ', ...
     'exterior-map shape retains the nonzero binomial dimension'];
metadata.reviewed_additive_zero_semantics = ...
    ['The pinned QETLAB dependency path errors at order zero; the native ', ...
     'derivative convention returns the 1-by-1 zero matrix'];

if exist('OCTAVE_VERSION', 'builtin')
    metadata.engine = 'Octave';
    metadata.engine_version = OCTAVE_VERSION;
    metadata.matlab_compatible_oracle = false;
else
    metadata.engine = 'MATLAB';
    metadata.engine_version = version;
    metadata.matlab_compatible_oracle = true;
end

payload = struct();
payload.metadata = metadata;
payload.fixtures = fixtures;
encoded = jsonencode(payload);

output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~exist(output_directory, 'dir')
    mkdir(output_directory);
end
file_id = fopen(output_path, 'w');
if file_id < 0
    error('QuantumEntanglementTools:OracleOutput', ...
        'Could not open the oracle output path for writing.');
end
cleanup_file = onCleanup(@() fclose(file_id));
fwrite(file_id, encoded, 'char');
fwrite(file_id, sprintf('\n'), 'char');

fprintf( ...
    'Wrote %d Tier E matrix-analysis fixtures (%d agreement, %d discrepancy) ', ...
    length(fixtures), agreement_count, discrepancy_count);
fprintf('to %s using %s %s.\n', ...
    output_path, metadata.engine, metadata.engine_version);
end

function fixture = oracle_fixture( ...
    name, value, comparison, atol, rtol, classification)
value = full(value);
fixture = struct();
fixture.name = name;
fixture.rows = size(value, 1);
fixture.columns = size(value, 2);
fixture.real = reshape(real(value), 1, numel(value));
fixture.imaginary = reshape(imag(value), 1, numel(value));
fixture.comparison = comparison;
fixture.atol = atol;
fixture.rtol = rtol;
fixture.classification = classification;
end

function remove_qetlab_paths(qetlab_path, helpers_path)
rmpath(helpers_path);
rmpath(qetlab_path);
end
